### PR TITLE
Fix sbt-web 1.4.0 api change plus version bumps

### PR DESCRIPTION
**Pull request by llinder**
Attempt at resurrecting https://github.com/sbt/sbt-uglify/pull/20 and also fixing syncMappins API change in SbtWeb 1.4.0

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @llinder,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johdah** [comment]
@llinder I missed your PR. Nice that I'm not alone in wanting this upgraded.

**Comment by llinder** [comment]
Yeah I actually stumbled upon a but with sbt-web where there was a breaking change on `SbtWeb.syncMappings` to improve some caching concerns.  Luckily @objectmastery did most of the legwork on getting uglify updated.  Now if we can just get the tests to pass.  `sbt scripted` is working fine locally but fails on Travis which makes things extra fun :/

**Comment by objectmastery** [comment]
I'm not entirely familiar with Travis beyond it being a CI tool, but looking at the log it spits out, it seems to be running tests on Java 1.6 for this project.

When it failed for my PR, Java full on crashed out, so I just ignored it thinking it was something on Travis's end.

It's failed on your PR again, but this time it didn't crash at the start. Looking at the error that occurs...

```
java.lang.UnsupportedClassVersionError: org/webjars/WebJarExtractor$Cache : Unsupported major.minor version 51.0
```

... it looks like the tests are failing because the jar referred to by that exception isn't compiled in Java 1.6.

Does someone need to reconfigure Travis to run tests with Java 1.8, perhaps?

**Comment by johdah** [comment]
@objectmastery in the root of the project there is a .travis.yml file that specifies which jdk to use. Replace it with oraclejdk8 and it will use that.

**Comment by llinder** [comment]
Looks like using openjdk7 did the trick.  Now just need to get a maintainer to approve and merge :)

**Comment by johdah** [comment]
@llinder Have you signed the CLA? If so I think you need to ping @typesafehub-validator again.

**Comment by llinder** [comment]
Thanks @johdah. I did sign the CLA through the Github process in the link they provided.  Not sure what what else to do get their attention on this.  Hopefully someone will chime in with comments soonish so I don't have to publish my own release :/

**Comment by ebruchez** [comment]
I tried this change locally and it appears to work. Thanks @linder. Unfortunately it seems that `sbt-web` in general is in need of some love or in need of a replacement.

**Comment by huntc** [comment]
So sorry for the lack of attention of late. We could do with some volunteers who'd be interested in putting a plan forward and become commuters. We've tried this already but got little response.

**Comment by ebruchez** [comment]
@huntc Do you happen to know why there is so little interest/activity on any `sbt-web` plugins?

**Comment by llinder** [comment]
@huntc `sbt-web` plugins are really awesome and it would be sad to see the project fall by the wayside.  I feel the simple solution is to just make more people committers.  If fixes like this aren't merged then folks will either give up hope or fork/publish their own builds.  Core committers such as yourself should probably focus on maintaining the core libraries and give more responsibility for plugin maintenance to a broader audience of community folks that are contributing fixes back.

**Comment by huntc** [comment]
I completely agree - Both @jroper and I are worked off our feet at the moment. I personally need to take a step out of what I'm doing right now and really think about the best way forward with sbt-web. Something will happen...

**Comment by benmccann** [comment]
@llinder I think most of this is in now since #20 was merged, but you also have some stuff that's new here. Would you be able to rebase so that we can see what the new changes are?

**Pull request merged**
